name: Google Analytics
version: 2.3.0
description: Google Analytics Reporting for Statamic V2
url: https://github.com/jrc9designstudio/statamic-google-analytics-v2
developer: JRC9 Design Studio
developer_url: https://github.com/jrc9designstudio
commercial: true
